### ISSUE TITLE
database timing

### ISSUE THREAD

**Issue by pschaub** [beyondcode/laravel-server-timing#10]
It would be great to see the time it took to get all the data from the database (if DB is used). Is there an easy way to integrate this for all DB requests?

**Comment by craftyshaun** [comment]
You could do this by listening to eloquent db events as per [Laravel database documentation](https://laravel.com/docs/7.x/database#listening-for-query-events) .

You could then add enteries for each query. It could expose SQL queries depending how you named them so you would have to be sure to run only on development.

**Comment by Radiergummi** [comment]
Anyone looking for a quick solution for this - add the following snippet to your `AppServiceProvider`:

```php
public function boot(): void
{
    // Make *sure* to only run this locally!
    if ( ! $this->app->environment('local')) {
        return;
    }

    DB::listen(function (QueryExecuted $query): void {
        ServerTiming::setDuration($query->sql, $query->time);
    });
}
```

Instantly yields the following:
<img width="365" alt="Bildschirmfoto 2021-02-22 um 13 47 50" src="https://user-images.githubusercontent.com/6115429/108710596-91274e00-7514-11eb-99d6-0b70acbd964a.png">

**Comment by SadeghPM** [comment]
And database total time. Safe for production:
```php
\DB::listen(function ($query): void {
    $previous = \Stopwatch::getDuration('Database')??0;
    \Stopwatch::setDuration('Database', $previous+$query->time);
});
```
![Screenshot from 2021-10-11 12-41-30](https://user-images.githubusercontent.com/9298600/136764561-fab04a05-dddf-4067-b980-7aefa98033f7.png)

**Comment by milanchheda** [comment]
Sorry to bother @SadeghPM , but can you tell me how did you use `Stopwatch` or basically what namespace did you added?
I have tried `use BeyondCode\ServerTiming\ServerTiming;` but it isn't working. 
We want to track query timings too and hence planning to add above code but somehow `ServerTiming` or `StopWatch` both aren't working..

**Comment by SadeghPM** [comment]
There is an aliases in  `composer.json` with name `Stopwatch`:
```json
            "aliases": {
                "Stopwatch": "BeyondCode\\ServerTiming\\Facades\\ServerTiming"
            }
```
Use this alias `\Stopwatch`.

**Comment by milanchheda** [comment]
Perfect. Thanks a bunch @SadeghPM!
