### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by eldair** [beyondcode/laravel-server-timing#14]
Hi,

Will this package support laravel 8?

**Comment by clementmas** [comment]
Yes, it already supports Laravel 8. See https://github.com/beyondcode/laravel-server-timing/pull/12

**Comment by nhalstead** [comment]
Someone has a PR ready, just waiting on a maintainer from beyondcode to approve and merge it #15

**Comment by eldair** [comment]
As far as I can see, another previous pull request was already merged. There is just no new release :|

**Comment by sschlein** [comment]
I've tagged 1.2, sorry for the delay
