### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by shevtsov-max** [beyondcode/laravel-server-timing#19]
When will php 8 support?

**Comment by justinhartman** [comment]
Second 👍🏿

**Comment by mpociot** [comment]
This is now in 1.2.0

**Comment by mmachatschek** [comment]
@mpociot it looks like the tagged version is missing the merged PRs https://github.com/beyondcode/laravel-server-timing/compare/1.1.0...1.2.0
