### ISSUE TITLE
Tag v1.2.0 doesn't contain all changes (PHP 8)

### ISSUE THREAD

**Issue by mmachatschek** [beyondcode/laravel-server-timing#20]
It seems like there was an issue with the last release (which should contain PHP 8 support) because the merged PRs are not in that tag.

https://github.com/beyondcode/laravel-server-timing/compare/1.1.0...1.2.0
https://github.com/beyondcode/laravel-server-timing/compare/1.1.0...master

https://github.com/beyondcode/laravel-server-timing/issues/19#issuecomment-748042390

**Comment by zlodes** [comment]
@mpociot Hi! Can you tag commit with PHP8 Support?

**Comment by slaFFik** [comment]
@mpociot We'd really love to get the PHP8 support :)

**Comment by leon0399** [comment]
any updates?

**Comment by efureev** [comment]
Create a tag `v1.2.1`, plz!

**Comment by a-h-abid** [comment]
@mpociot ... cannot install on PHP 8 using v1.2.0 .

Kindly please fix it.

**Comment by mpociot** [comment]
I just tagged 1.3.0, sorry that it took so long
