### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by jetwes** [beyondcode/laravel-server-timing#24]
Could you please add laravel 9 Support?

I added a PR #25

**Comment by emkcloud** [comment]
Could you please add laravel 9 Support?

**Comment by emkcloud** [comment]
> Could you please add laravel 9 Support?
> 
> I added a PR #25

News for PR Laravel 9 Support ?

**Comment by webard** [comment]
Here is good alternative: [mmachatschek](https://github.com/mmachatschek) / [laravel-server-timing](https://github.com/mmachatschek/laravel-server-timing)

**Comment by emkcloud** [comment]
> Here is good alternative: [mmachatschek](https://github.com/mmachatschek) / [laravel-server-timing](https://github.com/mmachatschek/laravel-server-timing)

Thank, I installed and is right... a few minutes and they managed to integrate it into the new installation

**Comment by khanhicetea** [comment]
Can we release a new tag to support Laravel 9 soon? I upgrade my application from 8 to 9 and be conflicted with dependencies.

Thanks!

**Comment by stebogit** [comment]
This update would be nice

**Comment by ulcuber** [comment]
Workaround `composer.json`:

```json
"beyondcode/laravel-server-timing": "dev-master",
```
