### ISSUE TITLE
Is this cool in production?

### ISSUE THREAD

**Issue by stebogit** [beyondcode/laravel-server-timing#27]
Is showing timings in production considered bad practice, or might cause issues of any kind?

**Comment by juliangarcess** [comment]
Hello @stebogit

On Google Chrome DevTools you can see: 

> During development, you can use [the Server Timing API](https://web.dev/custom-metrics/?utm_source=devtools#server-timing-api) to add insights into the server-side timing of this request.

The message suggests utilizing the Server Timing API just during the **development** phase.

Hope that helps.
